config/routes.rb
Rails.application.routes.draw do
  resources :kittens

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render(json: @kittens) }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render(json: @kitten) }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = 'Kitten was successfully created.'
      redirect_to @kitten
    else
      flash.now[:error] = 'Error while creating kitten.'
      render :new
    end
  end

  def update
    if @kitten.update(kitten_params)
      flash[:success] = 'Kitten was successfully updated.'
      redirect_to @kitten
    else
      flash[:error] = 'Error while updating kitten.'
      render :edit
    end
  end

  def destroy
    @kitten.destroy
    flash[:success] = 'Kitten was successfully destroyed.'
    redirect_to kittens_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
  <% if @kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
      <% @kitten.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :cuteness %><br>
    <%= f.number_field :cuteness %>
  </div>
  <div class="field">
    <%= f.label :softness %><br>
    <%= f.number_field :softness %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Editing Kitten</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitten %> |
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>Listing Kittens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.cuteness %></td>
        <td><%= kitten.softness %></td>
        <td><%= link_to 'Show', kitten %></td>
        <td><%= link_to 'Edit', edit_kitten_path(kitten) %></td>
        <td><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render 'form' %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @kitten.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @kitten.age %>
</p>

<p>
  <strong>Cuteness:</strong>
  <%= @kitten.cuteness %>
</p>

<p>
  <strong>Softness:</strong>
  <%= @kitten.softness %>
</p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Back', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |message_type, message| %>
<p><%= message %></p>
<% end %>

<%= yield %>

</body>
</html>